### ISSUE TITLE
Should have been done as a Python script

### ISSUE THREAD

**Issue by ctrlcctrlv** [fcambus/bdf2sfd#1]
This is just some friendly criticism, hopefully you'll find it constructive.

This should've been done via the FontForge Python API. We&dagger; recommend, in all cases, that third parties not write out SFDs, or try to manipulate them. Instead, our Python API should be used. SFD is not a well defined format.

Contours can easily be manipulated in our API, polygons can be created. Bitmap strikes can be read and written as well. If some needed function was missing, it should've been PR'd.

Keep in mind:

```
05:33:18 tarzeau feel free to star it, and open an issue?
05:39:30 @copypaste tarzeau: no need
05:39:44 @copypaste i'm not like, "in charge" of what other people do
05:39:55 @copypaste i'm not even "in charge" of what commits land in fontforge
05:40:14 @copypaste so i don't see a need to go on their bug tracker and spread negativity
05:40:39 tarzeau :)
[ ... snip ...]
05:53:33 tarzeau besides i wouldn't rate your opinion negative, but just opinion (constructive / neutral)
```

&dagger; "The FontForge Project" consensus, whatever that means.

**Comment by fcambus** [comment]
For this project it is too late now, but next time I will need to do something involving SFD files, I will have a look at the Python API.

Thanks for your feedback.
